# Generated by Django 2.0 on 2020-08-11 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_author_blog_entry'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyClassReource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '我的班级',
                'verbose_name_plural': '我的班级资源包',
                'db_table': 'user_to_resource',
            },
        ),
        migrations.CreateModel(
            name='ResourcePackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='资源名')),
                ('price', models.FloatField(default=1.0, verbose_name='报价')),
                ('sales', models.FloatField(default=1.0, verbose_name='实际售价')),
                ('uid', models.CharField(max_length=32, unique=True, verbose_name='资源包uid')),
            ],
            options={
                'verbose_name': '资源包',
                'verbose_name_plural': '资源包',
                'db_table': 'resource_package',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='学员昵称')),
                ('phone', models.CharField(max_length=14, unique=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
                ('avatar', models.CharField(max_length=256, verbose_name='头像')),
                ('real_name', models.CharField(max_length=50, verbose_name='真实姓名')),
                ('gender', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='出生日期')),
                ('education', models.IntegerField(choices=[(0, '初中'), (1, '高中'), (2, '大专'), (3, '本科'), (4, '硕士'), (5, '博士')], default=0, verbose_name='学历')),
                ('signature', models.CharField(max_length=500, verbose_name='签名')),
                ('learn_target', models.CharField(max_length=500, verbose_name='学习目的')),
                ('learn_goal', models.IntegerField(choices=[(0, '一年目标'), (1, '3-5 年目标'), (2, '长期目标')], verbose_name='学习目标')),
                ('address', models.CharField(max_length=200, verbose_name='收货地址')),
            ],
            options={
                'verbose_name': '学员',
                'verbose_name_plural': '学员',
                'db_table': 'student',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.IntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='myclassreource',
            name='resourcePackages',
            field=models.ManyToManyField(related_name='resource_package_id', to='polls.ResourcePackage'),
        ),
        migrations.AddField(
            model_name='myclassreource',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='student_id', to='polls.Student', verbose_name='资源'),
        ),
    ]
