# Generated by Django 2.0 on 2020-08-11 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20200811_1118'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myclassreource',
            name='resourcePackages',
        ),
        migrations.AddField(
            model_name='myclassreource',
            name='resourcePackages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='resource_package_id', to='polls.ResourcePackage'),
        ),
    ]
