# Generated by Django 2.0 on 2020-08-11 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20200811_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myclassreource',
            old_name='resourcePackages',
            new_name='rource',
        ),
    ]
