# Generated by Django 2.0 on 2020-08-17 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20200817_1433'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户表', 'verbose_name_plural': '客户表'},
        ),
        migrations.RemoveIndex(
            model_name='customer',
            name='polls_custo_last_na_41fb17_idx',
        ),
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together={('first_name', 'last_name')},
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['last_name', 'first_name'], name='sys_custome_last_na_6c035c_idx'),
        ),
        migrations.AlterModelTable(
            name='customer',
            table='sys_customer',
        ),
    ]
