# Generated by Django 2.0 on 2020-08-22 17:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20200819_1141'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDirecotryResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=180, null=True, verbose_name='描述')),
                ('enabled', models.BooleanField(default=True, verbose_name='有效')),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('delete_datetime', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='资源的名称')),
                ('num_id', models.IntegerField(verbose_name='章节顺序')),
                ('parent_id', models.IntegerField(null=True, verbose_name='父节点Id')),
                ('resource_id', models.CharField(max_length=50, verbose_name='资源id,属于哪个课程下的')),
                ('path', models.CharField(max_length=500, null=True, verbose_name='资源路径')),
                ('audition', models.BooleanField(default=False, verbose_name='是否可试听')),
            ],
            options={
                'verbose_name': '课程资源目录表',
                'verbose_name_plural': '课程资源目录表',
                'db_table': 'schedule_directory_resource',
            },
        ),
    ]
