# Generated by Django 2.0 on 2020-08-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_scheduledirecotryresource'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scheduledirecotryresource',
            name='num_id',
        ),
    ]
