# Generated by Django 2.0 on 2020-08-24 03:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_scheduledirecotryresource_num_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleDirecotryResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, default='', max_length=180, null=True, verbose_name='描述')),
                ('enabled', models.BooleanField(default=True, verbose_name='有效')),
                ('create_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间')),
                ('delete_datetime', models.DateTimeField(blank=True, null=True, verbose_name='删除时间')),
            ],
            options={
                'verbose_name': '课程资源类型表',
                'verbose_name_plural': '课程资源类型表',
                'db_table': 'schedule_directory_resource_type',
            },
        ),
        migrations.AddField(
            model_name='scheduledirecotryresource',
            name='num_id',
            field=models.IntegerField(null=True, verbose_name='章节顺序'),
        ),
        migrations.AddField(
            model_name='scheduledirecotryresource',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='schedule_directory_resource_type_id', to='polls.ScheduleDirecotryResourceType', verbose_name='讲的类型id'),
        ),
    ]
