# Generated by Django 2.0 on 2020-08-24 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20200824_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledirecotryresource',
            name='type',
            field=models.IntegerField(choices=[(1, '理论须知'), (2, '音频图文'), (3, '练习'), (4, '课件')], default=1, verbose_name='类型'),
        ),
        migrations.DeleteModel(
            name='ScheduleDirecotryResourceType',
        ),
    ]
