# Generated by Django 2.0.13 on 2020-10-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='金额'),
        ),
    ]
